//! The capture audit `self_check` runs before its recompute comparison
//! (#622 C9, acceptance A5; ADR-0013, "The capture audit").
//!
//! A captured table's changes reach the ring only through its four capture
//! triggers ([`crate::capture`]). A trigger an operator disabled or dropped,
//! a function handed to another owner, or a privilege revoked from the
//! Trellis role breaks that silently: nothing errors, the ring just stops
//! getting the table's changes, and the target goes stale. The table's
//! capture is also wrong once the table joins a partition or inheritance
//! hierarchy after its definition was accepted, because a statement trigger
//! fires only for the table a statement names (`defs::catalog::change_keyed`
//! refuses such a table at acceptance, but nothing refuses the later
//! `ATTACH PARTITION` or `INHERIT`).
//!
//! [`audit`] reads all of that from the catalog (`pg_trigger`, `pg_proc`,
//! `pg_inherits` and the `has_*_privilege` functions) for every table a
//! definition's target depends on, and reports each problem as a
//! [`CaptureFault`].
//!
//! # What the audit expects
//!
//! What `capture::install` installs (#622 plan Q3: one Trellis role does
//! everything):
//!
//! - **Four triggers per captured table**, named by
//!   [`crate::capture::sql::trigger_name`], each `ENABLE ALWAYS`
//!   (`tgenabled = 'A'`) and calling its event's function.
//! - **Four functions in the instance schema**, named by
//!   [`crate::capture::sql::function_name`], each `SECURITY DEFINER` and
//!   owned by the role that owns the instance schema.
//! - **The privileges a function's body uses, held by the role it runs
//!   as** (its owner): `USAGE` on the instance schema, `INSERT` on every
//!   ring segment, `USAGE` (or `UPDATE`) on `staging_change_id_seq`, which
//!   the segments' `change_id` default draws from, and `USAGE` (or
//!   `SELECT`) on `ring_slot_mirror`, which `pg_sequence_last_value` reads.
//!   The owner of the schema and the ring holds them all unless someone
//!   revokes them; a superuser always does.
//!
//! # Which definitions and tables
//!
//! Only a definition whose capture must already be installed is audited:
//! one that is `backfilling`, `catching_up` or `live`. A discharge dispatches
//! a waiting definition only once its tables are captured (see
//! `capture::reconcile`, "Which definitions a discharge may dispatch"), so
//! before that a missing trigger is expected. A paused or quarantined
//! definition is frozen and reads nothing until it resumes.
//!
//! The tables are the definition's source and the to-side of every
//! relationship it reads a column through, less any that is some
//! definition's target in this instance: the target-mutation seam feeds
//! those, not a trigger (`defs::tables_to_capture`).
//!
//! # What it doesn't check
//!
//! Whether the installed functions image every column the definitions now
//! read, or were generated by this build. Those change as definitions come
//! and go, and the staging worker's reconcile pass widens or replaces the
//! functions (holding back a definition until its columns are imaged), so a
//! mismatch there is the normal state between two passes, not a fault. The
//! same pass also repairs a missing or disabled trigger, so a fault this
//! audit reports persists only while no staging worker runs, or while the
//! pass can't land (its lock waits and failures are on `Trellis::status`).

use std::collections::BTreeSet;
use std::fmt;

use tokio_postgres::GenericClient;

use crate::capture::sql::{CaptureEvent, function_name, trigger_name};
use crate::defs::catalog::{self, CatalogError};
use crate::defs::model::{Definition, TransformStatus};
use crate::staging::append::RING_SIZE;

/// One way a table's capture is broken, found by [`audit`]. Each names the
/// captured table as its unquoted `schema.table` identity, except
/// [`CaptureFault::MissingPrivilege`], which is about the instance, not one
/// table.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum CaptureFault {
    /// None of the table's capture triggers or functions exist.
    NotInstalled { table: String },
    /// This trigger is missing from the table, while some of its other
    /// capture pieces exist.
    MissingTrigger { table: String, trigger: String },
    /// This trigger exists but isn't `ENABLE ALWAYS`. `enabled` is its
    /// `pg_trigger.tgenabled`: `D` (disabled), `O` (fires only in a session
    /// whose `session_replication_role` is `origin` or `local`) or `R` (fires
    /// only when it is `replica`).
    TriggerNotAlways {
        table: String,
        trigger: String,
        enabled: String,
    },
    /// This capture function (`schema.function`) is missing, while some of
    /// the table's other capture pieces exist.
    MissingFunction { table: String, function: String },
    /// This trigger calls some function other than `function`, its event's
    /// capture function.
    WrongFunction {
        table: String,
        trigger: String,
        function: String,
    },
    /// This capture function is owned by `owner`, not by `expected`, the role
    /// that owns the instance schema. It runs as its owner.
    FunctionOwner {
        table: String,
        function: String,
        owner: String,
        expected: String,
    },
    /// This capture function isn't `SECURITY DEFINER`, so it runs as
    /// whichever role writes the table, which needs privileges on Trellis's
    /// schema the application doesn't have.
    NotSecurityDefiner { table: String, function: String },
    /// `role`, which a capture function runs as, lacks `privilege` on
    /// `object`, which the function uses. A captured write then fails.
    MissingPrivilege {
        role: String,
        privilege: String,
        object: String,
    },
    /// The table became a partition of `parent` after its definition was
    /// accepted. A write through `parent` fires `parent`'s statement
    /// triggers, not the table's, so it isn't captured.
    Partition { table: String, parent: String },
    /// The table became an inheritance child of `parent`. A write through
    /// `parent` to the table's rows isn't captured.
    InheritanceChild { table: String, parent: String },
    /// `child` inherits from the table. A statement on the table that reaches
    /// `child`'s rows puts them in the table's transition tables, keyed as if
    /// they were the table's own.
    InheritanceParent { table: String, child: String },
}

impl CaptureFault {
    /// The captured table this fault is on, or `None` for
    /// [`CaptureFault::MissingPrivilege`].
    pub fn table(&self) -> Option<&str> {
        match self {
            CaptureFault::NotInstalled { table }
            | CaptureFault::MissingTrigger { table, .. }
            | CaptureFault::TriggerNotAlways { table, .. }
            | CaptureFault::MissingFunction { table, .. }
            | CaptureFault::WrongFunction { table, .. }
            | CaptureFault::FunctionOwner { table, .. }
            | CaptureFault::NotSecurityDefiner { table, .. }
            | CaptureFault::Partition { table, .. }
            | CaptureFault::InheritanceChild { table, .. }
            | CaptureFault::InheritanceParent { table, .. } => Some(table),
            CaptureFault::MissingPrivilege { .. } => None,
        }
    }
}

impl fmt::Display for CaptureFault {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CaptureFault::NotInstalled { table } => {
                write!(f, "{table} has no capture triggers or functions")
            }
            CaptureFault::MissingTrigger { table, trigger } => {
                write!(f, "the capture trigger {trigger} on {table} is missing")
            }
            CaptureFault::TriggerNotAlways {
                table,
                trigger,
                enabled,
            } => {
                let state = match enabled.as_str() {
                    "D" => "disabled",
                    "O" => "enabled only for origin sessions",
                    "R" => "enabled only for replica sessions",
                    _ => "not enabled",
                };
                write!(
                    f,
                    "the capture trigger {trigger} on {table} is {state} \
                     (tgenabled = {enabled}), not ENABLE ALWAYS"
                )
            }
            CaptureFault::MissingFunction { table, function } => {
                write!(f, "{table}'s capture function {function} is missing")
            }
            CaptureFault::WrongFunction {
                table,
                trigger,
                function,
            } => write!(
                f,
                "the capture trigger {trigger} on {table} doesn't call {function}"
            ),
            CaptureFault::FunctionOwner {
                table,
                function,
                owner,
                expected,
            } => write!(
                f,
                "{table}'s capture function {function} is owned by {owner}, not by {expected}, \
                 the owner of the Trellis schema"
            ),
            CaptureFault::NotSecurityDefiner { table, function } => write!(
                f,
                "{table}'s capture function {function} isn't SECURITY DEFINER"
            ),
            CaptureFault::MissingPrivilege {
                role,
                privilege,
                object,
            } => write!(
                f,
                "role {role}, which the capture functions run as, lacks {privilege} on {object}"
            ),
            CaptureFault::Partition { table, parent } => write!(
                f,
                "{table} became a partition of {parent}, so writes through {parent} aren't \
                 captured"
            ),
            CaptureFault::InheritanceChild { table, parent } => write!(
                f,
                "{table} inherits from {parent}, so writes through {parent} aren't captured"
            ),
            CaptureFault::InheritanceParent { table, child } => write!(
                f,
                "{child} inherits from {table}, so a statement on {table} captures {child}'s \
                 rows as {table}'s"
            ),
        }
    }
}

/// Every [`CaptureFault`] on the tables `def` reads, in a deterministic
/// order: per table (sorted), its trigger and function faults in event
/// order, then its hierarchy faults; then the privilege faults, per role.
/// Empty for a definition whose capture needn't be installed yet (see the
/// module doc).
pub async fn audit(
    client: &impl GenericClient,
    schema: &str,
    def: &Definition,
) -> Result<Vec<CaptureFault>, CatalogError> {
    if !matches!(
        def.status,
        TransformStatus::Backfilling | TransformStatus::CatchingUp | TransformStatus::Live
    ) {
        return Ok(Vec::new());
    }
    let mut faults = Vec::new();
    let mut runs_as = BTreeSet::new();
    for table in captured_tables(client, def).await? {
        let Some(installed) = read_installed(client, schema, &table).await? else {
            // A dropped table: the recompute's own read of it reports that.
            continue;
        };
        runs_as.extend(installed.events.iter().filter_map(|e| e.owner.clone()));
        faults.extend(installed_faults(&table, &installed));
        faults.extend(hierarchy_faults(client, &table).await?);
    }
    for role in runs_as {
        faults.extend(privilege_faults(client, schema, &role).await?);
    }
    Ok(faults)
}

/// The tables whose capture feeds `def`: its source and the to-side of each
/// relationship it reads through, less every table that is a definition's
/// target here (the seam feeds those). Sorted.
async fn captured_tables(
    client: &impl GenericClient,
    def: &Definition,
) -> Result<Vec<String>, CatalogError> {
    let mut tables = BTreeSet::from([def.source_table.clone()]);
    let names: BTreeSet<String> = crate::defs::eval::relationship_references(&def.def)
        .into_iter()
        .map(|(name, _)| name)
        .collect();
    if !names.is_empty()
        && let Some((from_schema, from_table)) = def.source_table.split_once('.')
    {
        for rel in catalog::relationships_from_table_in(client, from_schema, from_table).await? {
            if names.contains(&rel.def.name) {
                tables.insert(rel.qualified_to_table());
            }
        }
    }
    let tables: Vec<String> = tables.into_iter().collect();
    let seam_fed: BTreeSet<String> = client
        .query(
            "select target_table from transform_definitions where target_table = any($1)",
            &[&tables],
        )
        .await?
        .into_iter()
        .map(|row| row.get(0))
        .collect();
    Ok(tables
        .into_iter()
        .filter(|t| !seam_fed.contains(t))
        .collect())
}

/// One table's capture pieces, as the catalog has them.
#[derive(Debug, Clone, PartialEq, Eq)]
struct InstalledCapture {
    /// The role that owns the instance schema.
    schema_owner: String,
    /// One per [`CaptureEvent::ALL`], in that order.
    events: Vec<EventCapture>,
}

/// One event's trigger and function.
#[derive(Debug, Clone, PartialEq, Eq)]
struct EventCapture {
    /// The trigger's name.
    trigger: String,
    /// The function, qualified by the instance schema.
    function: String,
    /// `pg_trigger.tgenabled`, if the trigger exists.
    enabled: Option<String>,
    /// Whether the trigger calls this event's function.
    calls_function: bool,
    /// The function's owner, if the function exists.
    owner: Option<String>,
    /// Whether the function is `SECURITY DEFINER`.
    security_definer: bool,
}

/// Reads `table`'s triggers and functions in one statement. `None` if the
/// table doesn't exist.
async fn read_installed(
    client: &impl GenericClient,
    schema: &str,
    table: &str,
) -> Result<Option<InstalledCapture>, CatalogError> {
    // Only a name that isn't a `schema.table` identity has no function name,
    // and the catalog qualifies every table it records.
    let Ok(functions) = CaptureEvent::ALL
        .iter()
        .map(|event| function_name(table, *event))
        .collect::<Result<Vec<_>, _>>()
    else {
        return Ok(None);
    };
    let triggers: Vec<String> = CaptureEvent::ALL
        .iter()
        .map(|event| trigger_name(schema, *event))
        .collect();
    let rows = client
        .query(
            "select pg_catalog.to_regclass($3) is not null, \
                    pg_catalog.pg_get_userbyid(n.nspowner)::text, \
                    t.tgenabled::text, t.tgfoid = p.oid, \
                    pg_catalog.pg_get_userbyid(p.proowner)::text, p.prosecdef \
             from unnest($2::text[], $4::text[]) with ordinality as e(function, trigger, ord) \
             cross join (select oid, nspowner from pg_catalog.pg_namespace \
                         where nspname = $1) n \
             left join pg_catalog.pg_proc p \
               on p.proname = e.function and p.pronargs = 0 and p.pronamespace = n.oid \
             left join pg_catalog.pg_trigger t \
               on t.tgrelid = pg_catalog.to_regclass($3) and t.tgname = e.trigger \
              and not t.tgisinternal \
             order by e.ord",
            &[
                &schema,
                &functions,
                &crate::defs::ddl::regclass_arg(table),
                &triggers,
            ],
        )
        .await?;
    let Some(first) = rows.first() else {
        // No such schema: nothing of this instance's can be installed.
        return Ok(None);
    };
    if !first.get::<_, bool>(0) {
        return Ok(None);
    }
    let schema_owner: String = first.get(1);
    let events = rows
        .iter()
        .zip(functions)
        .zip(triggers)
        .map(|((row, function), trigger)| EventCapture {
            trigger,
            function: format!("{schema}.{function}"),
            enabled: row.get(2),
            calls_function: row.get::<_, Option<bool>>(3) == Some(true),
            owner: row.get(4),
            security_definer: row.get::<_, Option<bool>>(5) == Some(true),
        })
        .collect();
    Ok(Some(InstalledCapture {
        schema_owner,
        events,
    }))
}

/// The trigger and function faults of `installed`, one table's pieces: a
/// single [`CaptureFault::NotInstalled`] when none exist.
fn installed_faults(table: &str, installed: &InstalledCapture) -> Vec<CaptureFault> {
    if installed
        .events
        .iter()
        .all(|e| e.enabled.is_none() && e.owner.is_none())
    {
        return vec![CaptureFault::NotInstalled {
            table: table.to_string(),
        }];
    }
    let mut faults = Vec::new();
    for event in &installed.events {
        let table = table.to_string();
        match &event.enabled {
            None => faults.push(CaptureFault::MissingTrigger {
                table: table.clone(),
                trigger: event.trigger.clone(),
            }),
            Some(enabled) => {
                if enabled != "A" {
                    faults.push(CaptureFault::TriggerNotAlways {
                        table: table.clone(),
                        trigger: event.trigger.clone(),
                        enabled: enabled.clone(),
                    });
                }
                // A missing function is its own fault; the trigger can't
                // call it then, so saying so again would only repeat it.
                if event.owner.is_some() && !event.calls_function {
                    faults.push(CaptureFault::WrongFunction {
                        table: table.clone(),
                        trigger: event.trigger.clone(),
                        function: event.function.clone(),
                    });
                }
            }
        }
        match &event.owner {
            None => faults.push(CaptureFault::MissingFunction {
                table,
                function: event.function.clone(),
            }),
            Some(owner) => {
                if *owner != installed.schema_owner {
                    faults.push(CaptureFault::FunctionOwner {
                        table: table.clone(),
                        function: event.function.clone(),
                        owner: owner.clone(),
                        expected: installed.schema_owner.clone(),
                    });
                }
                if !event.security_definer {
                    faults.push(CaptureFault::NotSecurityDefiner {
                        table,
                        function: event.function.clone(),
                    });
                }
            }
        }
    }
    faults
}

/// A partition, inheritance-parent or inheritance-child fault for each
/// `pg_inherits` row naming `table`, either way.
async fn hierarchy_faults(
    client: &impl GenericClient,
    table: &str,
) -> Result<Vec<CaptureFault>, CatalogError> {
    let rows = client
        .query(
            "select case when c.relispartition then 'partition' else 'child' end, \
                    pn.nspname::text || '.' || p.relname::text \
             from pg_catalog.pg_inherits h \
             join pg_catalog.pg_class c on c.oid = h.inhrelid \
             join pg_catalog.pg_class p on p.oid = h.inhparent \
             join pg_catalog.pg_namespace pn on pn.oid = p.relnamespace \
             where h.inhrelid = pg_catalog.to_regclass($1) \
             union all \
             select 'parent', cn.nspname::text || '.' || c.relname::text \
             from pg_catalog.pg_inherits h \
             join pg_catalog.pg_class c on c.oid = h.inhrelid \
             join pg_catalog.pg_namespace cn on cn.oid = c.relnamespace \
             where h.inhparent = pg_catalog.to_regclass($1) \
             order by 1, 2",
            &[&crate::defs::ddl::regclass_arg(table)],
        )
        .await?;
    Ok(rows
        .into_iter()
        .map(|row| {
            let table = table.to_string();
            let other: String = row.get(1);
            match row.get::<_, &str>(0) {
                "partition" => CaptureFault::Partition {
                    table,
                    parent: other,
                },
                "child" => CaptureFault::InheritanceChild {
                    table,
                    parent: other,
                },
                _ => CaptureFault::InheritanceParent {
                    table,
                    child: other,
                },
            }
        })
        .collect())
}

/// Each privilege a capture function's body uses that `role` lacks (see the
/// module doc, "What the audit expects").
async fn privilege_faults(
    client: &impl GenericClient,
    schema: &str,
    role: &str,
) -> Result<Vec<CaptureFault>, CatalogError> {
    let rows = client
        .query(
            &format!(
                "select 'USAGE', pg_catalog.quote_ident($2), \
                        pg_catalog.has_schema_privilege($1::name, $2, 'USAGE') \
                 union all \
                 select 'INSERT', o, pg_catalog.has_table_privilege($1::name, o, 'INSERT') \
                 from (select pg_catalog.format('%I.%I', $2, 'seg_' || i) as o, i \
                       from pg_catalog.generate_series(0, {last}) as i) s \
                 union all \
                 select 'USAGE', o, \
                        pg_catalog.has_sequence_privilege($1::name, o, 'USAGE, UPDATE') \
                 from (select pg_catalog.format('%I.%I', $2, 'staging_change_id_seq') as o) s \
                 union all \
                 select 'USAGE', o, \
                        pg_catalog.has_sequence_privilege($1::name, o, 'USAGE, SELECT') \
                 from (select pg_catalog.format('%I.%I', $2, 'ring_slot_mirror') as o) s",
                last = RING_SIZE - 1
            ),
            &[&role, &schema],
        )
        .await?;
    Ok(rows
        .into_iter()
        .filter(|row| !row.get::<_, bool>(2))
        .map(|row| CaptureFault::MissingPrivilege {
            role: role.to_string(),
            privilege: row.get(0),
            object: row.get(1),
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn event(trigger: &str, enabled: Option<&str>, owner: Option<&str>) -> EventCapture {
        EventCapture {
            trigger: trigger.to_string(),
            function: format!("trellis.cap_{trigger}"),
            enabled: enabled.map(str::to_string),
            calls_function: enabled.is_some() && owner.is_some(),
            owner: owner.map(str::to_string),
            security_definer: owner.is_some(),
        }
    }

    fn installed(events: Vec<EventCapture>) -> InstalledCapture {
        InstalledCapture {
            schema_owner: "trellis_role".to_string(),
            events,
        }
    }

    fn complete() -> Vec<EventCapture> {
        ["insert", "update", "delete", "truncate"]
            .iter()
            .map(|e| event(e, Some("A"), Some("trellis_role")))
            .collect()
    }

    #[test]
    fn a_complete_install_has_no_fault() {
        assert_eq!(installed_faults("public.t", &installed(complete())), vec![]);
    }

    #[test]
    fn nothing_installed_is_one_fault_not_eight() {
        let events = ["insert", "update", "delete", "truncate"]
            .iter()
            .map(|e| event(e, None, None))
            .collect();
        assert_eq!(
            installed_faults("public.t", &installed(events)),
            vec![CaptureFault::NotInstalled {
                table: "public.t".to_string()
            }]
        );
    }

    #[test]
    fn a_trigger_that_isnt_enable_always_is_a_fault_whatever_its_other_state() {
        let mut events = complete();
        events[1].enabled = Some("D".to_string());
        events[2].enabled = Some("O".to_string());
        let faults = installed_faults("public.t", &installed(events));
        assert_eq!(
            faults,
            vec![
                CaptureFault::TriggerNotAlways {
                    table: "public.t".to_string(),
                    trigger: "update".to_string(),
                    enabled: "D".to_string(),
                },
                CaptureFault::TriggerNotAlways {
                    table: "public.t".to_string(),
                    trigger: "delete".to_string(),
                    enabled: "O".to_string(),
                },
            ]
        );
        assert!(
            faults[0].to_string().contains("is disabled"),
            "{}",
            faults[0]
        );
    }

    #[test]
    fn a_missing_function_is_not_also_reported_as_the_trigger_calling_something_else() {
        let mut events = complete();
        events[0].owner = None;
        events[0].calls_function = false;
        events[0].security_definer = false;
        assert_eq!(
            installed_faults("public.t", &installed(events)),
            vec![CaptureFault::MissingFunction {
                table: "public.t".to_string(),
                function: "trellis.cap_insert".to_string(),
            }]
        );
    }

    #[test]
    fn a_trigger_calling_another_function_a_foreign_owner_and_an_invoker_function_are_faults() {
        let mut events = complete();
        events[0].calls_function = false;
        events[1].owner = Some("someone_else".to_string());
        events[2].security_definer = false;
        events[3].enabled = None;
        assert_eq!(
            installed_faults("public.t", &installed(events)),
            vec![
                CaptureFault::WrongFunction {
                    table: "public.t".to_string(),
                    trigger: "insert".to_string(),
                    function: "trellis.cap_insert".to_string(),
                },
                CaptureFault::FunctionOwner {
                    table: "public.t".to_string(),
                    function: "trellis.cap_update".to_string(),
                    owner: "someone_else".to_string(),
                    expected: "trellis_role".to_string(),
                },
                CaptureFault::NotSecurityDefiner {
                    table: "public.t".to_string(),
                    function: "trellis.cap_delete".to_string(),
                },
                CaptureFault::MissingTrigger {
                    table: "public.t".to_string(),
                    trigger: "truncate".to_string(),
                },
            ]
        );
    }
}
