-- Settled parent projection catalog (issue #129, epic #127 "relationship
-- delta"). See `trellis/tests/spikes/issue-102-PLAN-DRAFT.md` §2 ("The
-- mechanism") for the full design this is the first building block of — in
-- short: a to-one relationship's projection is a per-to-side-row table
-- holding exactly the to-side columns its consumers read, keyed by the
-- to-side primary/unique key, kept in step with the source by a forward
-- resolve path (#130) and a reverse delta (#131) later issues in this epic
-- wire up. This table only records *that* a projection exists and which
-- physical table backs it; the projection's own live data columns and
-- per-row bookkeeping (`__trellis_gen`/`__trellis_lsn`, see
-- `defs::ddl::PROJECTION_GEN_COLUMN`/`PROJECTION_LSN_COLUMN`) live on that
-- physical table, not here.
--
-- One row per **to-one** relationship
-- (`relationship_definitions.cardinality = 'one'`); a to-many relationship
-- never gets one — Phase 1 of the mechanism (this epic) is to-one
-- relationship *values* only. A to-many relationship's aggregate reads
-- already go through a different, existing delta path
-- (`staging::apply_aggregate`'s `rel_joins` / `defs::backfill`'s to-many
-- leaf staging), which this epic doesn't touch.
--
-- `relationship_id` is `unique`, not just indexed: exactly one projection
-- per relationship, ever — `defs::catalog::ensure_relationship_projection_in_txn`
-- relies on "does a row already exist for this id" to decide "create from
-- scratch" vs. "widen what's there", and a second row for the same
-- relationship would make that check ambiguous. `on delete cascade` even
-- though nothing deletes a `relationship_definitions` row today (v1
-- relationships, like v1 transform definitions, are immutable/undeletable
-- past creation) — matching `backfill_chunks`' identical
-- `references transform_definitions (id) on delete cascade`
-- (`V20__backfill_chunks.sql`) for the same "child row has no independent
-- reason to outlive its parent" reasoning, ahead of whenever a `DROP
-- RELATIONSHIP` might land.
--
-- `projection_table` is the physical table's bare name
-- (`defs::ddl::relationship_projection_table_name`,
-- `_trellis_rel_projection_<id>`), created in this instance's own schema
-- alongside this table, never the target schema (issue #435: another
-- instance sharing the target schema numbers its relationships from 1 too).
-- Named after the relationship's
-- catalog id rather than its declared name because a relationship name is
-- only unique *per from-table* (`V16__relationship_definitions.sql`), so two
-- differently-from-tabled relationships could otherwise collide; the id is
-- already unique within this catalog by the time the projection is created
-- (`create_relationship` inserts the `relationship_definitions` row first,
-- in the same transaction). `unique` here too, even though it's already
-- functionally unique by construction (one id, one deterministic name) — a
-- real constraint costs nothing and catches a future naming-scheme bug
-- loudly instead of silently colliding two projections onto one physical
-- table.
--
-- The union of to-side columns actually projected is **not** cached here,
-- unlike `transform_definitions.source_columns`
-- (`V12__transform_definitions_source_columns.sql`, persisted because the
-- Rust evaluator needs a definition's column types without a DB round trip
-- at CDC-apply time). The projection table is entirely Trellis-owned, never
-- read by anything outside this crate, so its current column set is always
-- introspected live off `information_schema.columns` at the one call site
-- that needs it (widening, when a new consumer is defined) — caching it
-- here would just be a second, driftable copy of what `pg_catalog` already
-- answers authoritatively for a table Trellis itself creates and alters.
create table if not exists relationship_projections (
    id bigint primary key generated always as identity,
    relationship_id bigint not null unique references relationship_definitions (id) on delete cascade,
    projection_table text not null unique,
    created_at timestamptz not null default now()
);
